# Generated by Django 3.1.4 on 2020-12-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_auto_20201213_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledge',
            options={'ordering': ['date_update'], 'verbose_name': 'Pledge', 'verbose_name_plural': "Pledge's"},
        ),
        migrations.AlterField(
            model_name='pledge',
            name='approved_date',
            field=models.DateTimeField(null=True, verbose_name='approved_date'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date_update'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='is_approved',
            field=models.BooleanField(null=True, verbose_name='is_approved'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='kfupm_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='kfupm_gpa'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='next_tearm',
            field=models.IntegerField(verbose_name='next_tearm'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='phone_guardian',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone_guardian'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='pledge_type',
            field=models.CharField(choices=[('S', 'condition'), ('D1', 'final'), ('D', 'dismiss')], max_length=2, verbose_name='pledge_type'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
    ]
