# Generated by Django 3.1.4 on 2020-12-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201214_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledge',
            options={'ordering': ['date_update'], 'verbose_name': 'Pledge', 'verbose_name_plural': 'Pledges'},
        ),
    ]
