# Generated by Django 3.1.4 on 2020-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201215_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='low_performance_reasons',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('PHYSICAL', 'Psychological'), ('FAMILY', 'Family circumstances'), ('STUDY', 'Study difficulties related to (major / academic courses)'), ('OTHER', 'other')], max_length=10, null=True, verbose_name='low_performance_reasons'),
        ),
    ]
