# Generated by Django 3.1.4 on 2020-12-17 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_pledge_low_performance_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledge',
            options={'ordering': ['date_added'], 'verbose_name': 'Pledge', 'verbose_name_plural': 'Pledges'},
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='date_update',
        ),
        migrations.AddField(
            model_name='pledge',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='approved_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='approved_date'),
            preserve_default=False,
        ),
    ]
