# Generated by Django 3.1.4 on 2020-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201217_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='low_performance_reasons',
            field=models.CharField(max_length=100, null=True, verbose_name='low_performance_reasons'),
        ),
    ]
