# Generated by Django 3.1.4 on 2020-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201220_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='guardian_relation',
            field=models.CharField(max_length=100, null=True, verbose_name='guardian_relation'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='low_performance_other_reasons',
            field=models.CharField(max_length=300, null=True, verbose_name='low_performance_other_reasons'),
        ),
    ]
