# Generated by Django 3.1.4 on 2020-12-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20201221_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='guardian_relation'),
        ),
    ]
