# Generated by Django 3.1.4 on 2020-12-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20201221_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='low_performance_other_reasons',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='low_performance_other_reasons'),
        ),
    ]
