# Generated by Django 3.1.4 on 2020-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20201227_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='pledge_type',
            field=models.CharField(choices=[('S', 'condition'), ('S1', 'final'), ('D', 'dismiss')], max_length=2, verbose_name='Pledge Type'),
        ),
    ]
