# Generated by Django 3.1.4 on 2020-12-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20201228_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
